/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasirestoran.kelompok6.pbo.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import aplikasirestoran.kelompok6.pbo.config.Koneksi;
import aplikasirestoran.kelompok6.pbo.controller.PelangganController;
import aplikasirestoran.kelompok6.pbo.event.PelangganListener;
import aplikasirestoran.kelompok6.pbo.model.PelangganModel;
import aplikasirestoran.kelompok6.pbo.view.AdminView;

/**
 *
 * @author asus
 */
public class PelangganView extends javax.swing.JFrame implements PelangganListener {

    private PelangganModel model;
    private PelangganController controller;
    /**
     * Creates new form MenuPelangganView
     */
    public PelangganView() {
        model = new PelangganModel();
        controller = new PelangganController();
        
        model.setPelangganListener(this);
        controller.setModel(model);
        
        initComponents();
        
        tampilCbMakanan();
        tampilCbMinuman();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    public javax.swing.JComboBox<String> getCmbMakanan() {
        return cmbMakanan;
    }
    public javax.swing.JComboBox<String> getCmbMinuman() {
        return cmbMinuman;
    }
    public javax.swing.JTextField getTxtHargaMakan() {
        return txtHargaMakan;
    }
    public javax.swing.JTextField getTxtHargaMinum() {
        return txtHargaMinum;
    }
    public javax.swing.JTextField getTxtNama() {
        return txtNama;
    }
    public javax.swing.JTextField getTxtQtyMakan() {
        return txtQtyMakan;
    }
    public javax.swing.JTextField getTxtQtyMinum() {
        return txtQtyMinum;
    }
    public javax.swing.JTextField getTxtTotal() {
        return txtTotal;
    }
    
    int _makanan;
    int _minuman;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmbMinuman = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbMakanan = new javax.swing.JComboBox<>();
        txtQtyMinum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHargaMinum = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtHargaMakan = new javax.swing.JTextField();
        txtQtyMakan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PELANGGAN ");
        setPreferredSize(new java.awt.Dimension(800, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        bodyPanel.setBackground(new java.awt.Color(192, 57, 43));
        bodyPanel.setMinimumSize(new java.awt.Dimension(800, 650));
        bodyPanel.setPreferredSize(new java.awt.Dimension(800, 690));
        bodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(192, 57, 43));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Minuman" }));
        cmbMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMinumanActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMinuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 170, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Minuman  ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        cmbMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Makanan" }));
        cmbMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMakananActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 40));

        txtQtyMinum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQtyMinum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtyMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyMinumActionPerformed(evt);
            }
        });
        txtQtyMinum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyMinumKeyReleased(evt);
            }
        });
        jPanel2.add(txtQtyMinum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Makanan  ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Jumlah  :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        txtHargaMinum.setEditable(false);
        txtHargaMinum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHargaMinum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHargaMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMinumActionPerformed(evt);
            }
        });
        jPanel2.add(txtHargaMinum, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 120, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Harga :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Harga :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Jumlah  :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtHargaMakan.setEditable(false);
        txtHargaMakan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHargaMakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHargaMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMakanActionPerformed(evt);
            }
        });
        jPanel2.add(txtHargaMakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 30));

        txtQtyMakan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtQtyMakan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtyMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyMakanActionPerformed(evt);
            }
        });
        txtQtyMakan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyMakanKeyReleased(evt);
            }
        });
        jPanel2.add(txtQtyMakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 30, 30));

        bodyPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 680, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU PILIHAN ");
        bodyPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btnPesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesanMouseClicked(evt);
            }
        });
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        bodyPanel.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 110, 50));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        bodyPanel.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 110, 50));

        jPanel4.setBackground(new java.awt.Color(192, 57, 43));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BEST SELLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(255, 255, 102))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasirestoran/kelompok6/pbo/icon/takoyaki.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasirestoran/kelompok6/pbo/icon/mieayam.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasirestoran/kelompok6/pbo/icon/roti.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 130, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ROTI BAKAR");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TAKOYAKI");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 70, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MIE AYAM");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 70, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasirestoran/kelompok6/pbo/icon/jempol.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, 50));

        bodyPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 720, 260));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 102));
        bodyPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 830, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 102));
        bodyPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 320, 10));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 102));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 102));
        bodyPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 320, 10));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama Pemesan :");
        bodyPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        bodyPanel.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 150, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Bayar :");
        bodyPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        bodyPanel.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 150, 30));

        getContentPane().add(bodyPanel, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMinumanActionPerformed
        // TODO add your handling code here:
        String input = getCmbMinuman().getSelectedItem().toString();
        
        try {
            Connection con = new Koneksi ().konek();
            String sql = "SELECT * FROM minuman WHERE nama_minuman =?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, input);
            
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
               _minuman = Integer.parseInt(rs.getString("id_minuman"));
                getTxtHargaMinum().setText(rs.getString("harga_minuman"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmbMinumanActionPerformed

    private void cmbMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMakananActionPerformed
        String input = getCmbMakanan().getSelectedItem().toString();
        
        try {
            Connection con = new Koneksi ().konek();
            String sql = "SELECT * FROM makanan WHERE nama_makanan =?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, input);
            
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
               _makanan = Integer.parseInt(rs.getString("id_makanan"));
                getTxtHargaMakan().setText(rs.getString("harga_makanan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cmbMakananActionPerformed

    private void txtQtyMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyMinumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyMinumActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtHargaMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMinumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMinumActionPerformed

    private void txtHargaMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMakanActionPerformed

    private void txtQtyMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyMakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyMakanActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseClicked
        controller.kirimPesanan(this);
    }//GEN-LAST:event_btnPesanMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        controller.resetPesanan(this);
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        
    }//GEN-LAST:event_btnPesanActionPerformed

    private void txtQtyMinumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyMinumKeyReleased
      controller.hitungTotalAuto(this);
    }//GEN-LAST:event_txtQtyMinumKeyReleased

    private void txtQtyMakanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyMakanKeyReleased
//      controller.hitungTotalAuto(this); 
    }//GEN-LAST:event_txtQtyMakanKeyReleased
   
    public void tampilCbMakanan(){
        try {
            Connection con = new Koneksi().konek();
            String sql = "SELECT * FROM makanan ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                getCmbMakanan().addItem(rs.getString("nama_makanan"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }
    public void tampilCbMinuman(){
        try {
            Connection con = new Koneksi().konek();
            String sql = "SELECT * FROM minuman ";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                getCmbMinuman().addItem(rs.getString("nama_minuman"));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }
    public void tampilAdminView(){
        AdminView admin = new AdminView();
        admin.setVisible(true);
        this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PelangganView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbMakanan;
    private javax.swing.JComboBox<String> cmbMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtHargaMakan;
    private javax.swing.JTextField txtHargaMinum;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtQtyMakan;
    private javax.swing.JTextField txtQtyMinum;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PelangganModel pelanggan) {
//        this.cmbMakanan.setSelectedItem(pelanggan.getNamaMakanan());
//        this.cmbMinuman.setSelectedItem(pelanggan.getNamaMinuman());
//        this.txtQtyMakan.setText(pelanggan.getTmakanan());
        
    }


}
